@Auth_HostAddress = http://localhost:5001

GET {{Auth_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Auth_HostAddress}}/blog/

###
POST  {{Auth_HostAddress}}/blog/
Content-Type: application/json

{
    "Title":"My Title",
    "Description":"My Description"

}
###
POST  {{Auth_HostAddress}}/api/authentication/register
Content-Type: application/json

{
    "name":"ewUwede7",
    "email":"ewcSere-1@gmail1sw34.com",
    "password":"0Dsfaksdnfasdf!"
}
###
POST  {{Auth_HostAddress}}/api/authentication/login
Content-Type: application/json

{
    "email":"aryanbaral@gmail.com",
    "password":"0Dsfaksdnfasdf!"
}

###
POST  {{Auth_HostAddress}}/api/authentication/refreshtoken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJmZDBjYTM5LTc1NTctNGM5MS1hNTk2LTA5YjIxM2JhOTM1MyIsInN1YiI6ImFyeWFuYmFyYWxAZ21haWwuY29tIiwiZW1haWwiOiJhcnlhbmJhcmFsQGdtYWlsLmNvbSIsImp0aSI6ImVlOTBhZjhkLWJmZGUtNDc5NS05MWI0LTk0MTg4NDg2OGNlNSIsImlhdCI6MTcyODI3MjA4NCwibmJmIjoxNzI4MjcyMDg0LCJleHAiOjE3MjgyNzIxNDR9.YTKmqc_aflZgKt5OHqQSepPbH7WV6ioHEf1WGr6cQow",
  "refreshToken": "04lGOfyKdFZLAOMceqlOMPZ"
}


