@Auth_HostAddress = http://localhost:5001

GET {{Auth_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Auth_HostAddress}}/blog/

###
POST  {{Auth_HostAddress}}/blog/
Content-Type: application/json

{
    "Title":"My Title",
    "Description":"My Description"

}


